# -*- coding: utf-8 -*-
"""02 Dash - Mise en page

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHro9Tby4vMmWPVXEjQUAV2J4RO3RgQ0
"""

from dash import Dash, html, dcc, Input, Output
import plotly.express as px
import pandas as pd

link = "https://raw.githubusercontent.com/chriszapp/datasets/main/books.csv"
df_books = pd.read_csv(link, on_bad_lines="skip")
df_books.head()

df_books_ten = df_books.sort_values("ratings_count", ascending=0).head(10)
df_books_ten

# Création de l'application
app = Dash(__name__)

fig = px.histogram(df_books_ten, x="title", y="  num_pages")

app.layout = html.Div([
    html.H1("The 10 best books, by reviews"),
    dcc.Graph(figure=fig),
    html.I("Choose an author:"),
    dcc.Dropdown(df_books_ten["authors"]),
    html.I("Type a max number of pages:"),
        html.Br(),
        dcc.Input(id="input1", type="number", placeholder="", style={'marginRight':'10px'})
])

# Exécution de l'application
if __name__ == '__main__':
    app.run_server(debug=True)